name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || github.event_name == 'workflow_dispatch')
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Verify source files
        run: |
          echo "Source files:"
          ls -la
          [ -f index.html ] && echo "✓ Source files ready" || echo "❌ Source files missing"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Verify Docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_sha }}
          echo "✓ Docker image built and pushed successfully"

      - name: Deployment notification
        run: |
          echo "🚀 DEPLOYMENT COMPLETE"
          echo "Image: ghcr.io/${{ github.repository }}:${{ github.event.workflow_run.head_sha }}"
