name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Triggered after CI succeeds
    types:
      - completed

jobs:
  docker-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact from CI
        uses: actions/download-artifact@v3
        with:
          name: project-artifact
          path: ./dist

      - name: Build Docker image
        run: docker build -t myusername/myapp:latest .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push myusername/myapp:latest
