name: Continuous Deployment

on:
  push:
    branches: [ main ]
  # Optional: Manual trigger for deployment
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # Only run if CI was successful
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app-build
          path: dist/

      - name: Verify deployment package
        run: |
          echo "Verifying deployment package..."
          cd dist
          ls -la
          if [ ! -f index.html ]; then
            echo "❌ Deployment package is missing index.html"
            exit 1
          fi
          echo "✓ Deployment package verified"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy notification
        run: |
          echo "🚀 Deployment ready!"
          echo "Docker image: ghcr.io/${{ github.repository }}:${{ github.sha }}"
          echo "Deployment package available in artifacts"

  # Optional: Deployment to staging environment
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app-build
          path: dist/

      - name: Build Staging Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ github.repository }}:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Staging deployment notification
        run: |
          echo "🎭 Staging deployment ready for testing"
          echo "Run: docker run -p 8080:80 ${{ github.repository }}:staging"
